//
//  ChoiceAPI.swift
//  Wanderlust
//
//  Created by Mihikaa Goenka on 8/8/19.
//  Copyright © 2019 Mihikaa Goenka. All rights reserved.
//

import Foundation
import UIKit

class ChoiceAPI {
    
    static func getPlaces() -> [Place]{
        let liv = Place(placeTitle: "Liv Nightclub at Fountainbleau", placeLocation: "Miami", placeType: .club, placeDescription: "Trendy, opulent Fontainebleau Hotel club where DJs spin at parties that attract celebs & VIPs.", placeImage: #imageLiteral(resourceName: "liv.jpg"), address: "4441 Collins Ave, Miami Beach, FL 33140, USA")
        let empire = Place(placeTitle: "Empire State Building", placeLocation: "New York City", placeType: .site, placeDescription: "Opened in 1931, the Empire State Building is the world's most famous office building, a historical landmark, and was named America's Favorite Architecture in a poll conducted by the American Institute of Architects. Its no surprise that visiting this amazing building is one of the top places to visit in New York.", placeImage:#imageLiteral(resourceName: "empire.png") , address: "20 W 34th St, New York, NY 10001, USA")
        let fenchurch = Place(placeTitle: "Fenchurch Sky Garden", placeLocation: "Cape Town", placeType: .restaurant, placeDescription: "Known as the walkie talkie due to its unique shape, this skyscraper features a top-floor restaurant.", placeImage: #imageLiteral(resourceName: "fenchurch.jpg"), address: "20 Fenchurch St, London EC3M 8AF, UK")
        let cullinan = Place(placeTitle: "Southern Sun The Cullinan", placeLocation: "Paris", placeType: .hotel, placeDescription: "This luxe hotel overlooking Plettenberg Bay is 8.2 km from Robberg Nature Reserve and 23 km from Monkeyland.", placeImage: #imageLiteral(resourceName: "cullinan.jpg") , address: "1 Cullinan St, Cape Town City Centre, Cape Town, 8001, South Africa")
        let space = Place(placeTitle: "Club Space", placeLocation: "Miami", placeType: .club, placeDescription: "It's the place all good nights go to transform into holy-shit-how-am-I-still-standing afternoons. The Ground is Space's poppin' live-music venue on the first floor that Miami didn't know it needed. It has found renewed spirit since the guys behind III Points and Link Miami Rebels took over.", placeImage: #imageLiteral(resourceName: "space.jpg"), address: "34 NE 11th St")
        let elleven = Place(placeTitle: "E11even", placeLocation: "Miami", placeType: .club, placeDescription: "It's part cabaret, part megaclub, and all rap-music-video fantasyland. E11even is the party that never stops. The 24-hour club has been open round-the-clock since February 2014 and is ready for your all-night ragers any night of the week.", placeImage: #imageLiteral(resourceName: "elleven.jpg"), address: "29 NE 11th St.")
        let o_six = Place(placeTitle: "1306", placeLocation: "Miami", placeType: .club, placeDescription: "Whether you want to chill out with a cocktail at the classy indoor bar or get down and dirty in the fresh air of the back patio, 1306 has something for everyone. Brought to you by the people who made Grand Central, a legend of downtown's old scene, 1306 has been known to book trivia nights, jam nights, big-ticket DJ sets, and special performances you don't want to miss.", placeImage: #imageLiteral(resourceName: "o_six.jpg"), address: "1306 N. Miami Ave.")
        let floyd = Place(placeTitle: "Floyd", placeLocation: "Miami", placeType: .club, placeDescription: "Technically, it's part of Club Space, but Floyd boasts a whole different vibe. Craft cocktails and close quarters lend the dimly lit room a classier, sultry mood, but if you come for one of the special events, the luxuriously decorated space rocks with the best of them. Offering genres from lo-fi house to French-touch classics, Floyd is an elevated turn-up experience for those who like to boogie and look good doing it.", placeImage:#imageLiteral(resourceName: "floyd.jpg"), address: "34 NE 11th St., Suite B")
        let intercontinental = Place(placeTitle: "Intercontinental Miami", placeLocation: "Miami", placeType: .hotel, placeDescription: "Refined rooms & suites in a plush high-rise property with a rooftop pool, a spa & fine dining.", placeImage: #imageLiteral(resourceName: "intercontinental.jpg"), address: "100 Chopin Plaza, FL 33131, USA")
        let mandarin = Place(placeTitle: "Mandarin Oriental", placeLocation: "Miami", placeType: .hotel, placeDescription: "This luxury hotel is a mile from Bayfront Park and 2 miles from sports and live music at the American Airlines Arena. It houses a private beach & an infinity pool, plus sophisticated dining & a spa.", placeImage: #imageLiteral(resourceName: "mandarin.jpeg"), address: "500 Brickell Key Dr")
        let four_seasons = Place(placeTitle: "Four Seasons, Miami", placeLocation: "Miami", placeType: .hotel, placeDescription: "Upscale hotel featuring a 2-acre pool area with cabanas, plus a spa, dining & bay views. Set in the financial district, this upscale hotel overlooking Biscayne Bay is 1.7 miles from the Vizcaya Museum & Gardens.", placeImage: #imageLiteral(resourceName: "four_seasons.jpg"), address: "1435 Brickell Ave")
        let hyatt_miami = Place(placeTitle: "Hyatt, Miami", placeLocation: "Miami", placeType: .hotel, placeDescription: "Hyatt Regency Miami sits next to the heart of Brickell, one of the trendiest neighborhoods in Miami. With its iconic white towers overlooking the Miami River, our hotel is connected to the James L. Knight Center. Our location puts you steps from the Miami Riverwalk and less than ten minutes from the Port of Miami. Take a short walk to the free Metromover station and ride to destinations like Coral Gables or the Wynwood Arts District. Shop the Brickell City Centre, less than ten minutes away, visit Little Havana to experience authentic Latin cuisine, or explore the Phillip and Patricia Frost Museum of Science." , placeImage:#imageLiteral(resourceName: "hyatt_miami.jpg") , address: "400 South East Second Avenue")
        let kyu = Place(placeTitle: "KYU", placeLocation: "Miami", placeType: .restaurant, placeDescription: "Modern Asian-style eatery offering grilled meats & sashimi, plus cocktails. Kyu has been dazzling locals and food critics alike with its creative Asian-inspired dishes, most of which are cooked over the open flames of a wood-fired grill. ", placeImage: #imageLiteral(resourceName: "kyu.jpg"), address: "251 North West 25th Street, 33127")
        let capital = Place(placeTitle: "The Capital Grille", placeLocation: "Miami", placeType: .restaurant, placeDescription: "Outpost of the upscale steakhouse chain offers classic American fare & a clubby, refined setting. Located on the Capitol Hill of Miami’s business movers and shakers, this is the quintessential spot for a power lunch.", placeImage: #imageLiteral(resourceName: "capital.jpg"), address: "444 Brickell Ave, FL 33131")
        let joes = Place(placeTitle: "Joe's Crab Shack", placeLocation: "Miami", placeType: .restaurant, placeDescription: "Cavernous, bustling space open October-May & drawing crowds for crab, Key lime pie & more. Cavernous, bustling space open October-May & drawing crowds for crab, Key lime pie & more.", placeImage: #imageLiteral(resourceName: "joes.jpg"), address: "1000 S Miami Avenue, FL 33130")
        let dolores = Place(placeTitle: "Dolores But You Can Call Me Lolita", placeLocation: "Miami", placeType: .restaurant, placeDescription: "Upstairs Dolores & terrace dishes eclectic cuisine, while downstairs Lolita serves up DJs & dancing. Peak wait up to 15 mins from 12:00 am – 12:00 am. People typically spend 1.5-2.5 hours here.", placeImage: #imageLiteral(resourceName: "dolores.jpg"), address: "1000 S Miami Ave, FL 33130")
        let novecento = Place(placeTitle: "Novecento", placeLocation: "Miami", placeType: .restaurant, placeDescription: "Bistro chain serving a menu of Argentinian dishes & Italian pastas, plus wine & cocktails. The crowd and ambience is electrifying.", placeImage: #imageLiteral(resourceName: "novecento.jpg"), address: "1414 Brickell Ave, FL 33131, USA")
        let everglades = Place(placeTitle: "Everglades", placeLocation: "Miami", placeType: .site, placeDescription: "Journey away from the city for an informative and relaxing ride through the beautiful Everglades. Embark on an exciting airboat adventure, check out alligators and other swamp critters during a wildlife show, and enjoy convenient transportation from your Miami hotel.", placeImage:#imageLiteral(resourceName: "everglades.jpg") , address: "Southern-most point of tropical Florida")
        let seaaquarium = Place(placeTitle: "Miami Seaquarium", placeLocation: "Miami", placeType: .site, placeDescription: "The Miami Seaquarium is a 38-acre oceanarium located on the island of Virginia Key in Biscayne Bay, Miami-Dade County, Florida, United States and is located near downtown Miami. ", placeImage:#imageLiteral(resourceName: "seaquarium.jpg") , address: "4400 Rickenbacker Causeway,FL 33149")
        let key_west = Place(placeTitle: "Key West", placeLocation: "Miami", placeType: .site, placeDescription: "Key West, a U.S. island city, is part of the Florida Keys archipelago. It's also Florida's southernmost point, lying roughly 90 miles north of Cuba. Famed for its pastel-hued, conch-style houses, it’s a cruise-ship stop also accessible from the mainland via the Overseas Highway. It’s known more for its coral reefs – destinations for diving and snorkeling – than for its beaches.", placeImage: #imageLiteral(resourceName: "key_west.jpg"), address: "Cayo Hueso, 33040 and 33041")
        let south_beach = Place(placeTitle: "South Beach", placeLocation: "Miami", placeType: .site, placeDescription: "South Beach is known for its beaches and the glamorous scene around its happening nightspots and celebrity-chef eateries. Chain stores and indie fashion shops line pedestrian shopping strip Lincoln Road Mall. On Ocean Drive, known for its well-preserved art deco architecture, outdoor cafes offer a ringside view of the scene.", placeImage: #imageLiteral(resourceName: "south_beach.jpg"), address: "Area Code 786")

        
        let places = [liv, empire, fenchurch, cullinan, space, elleven, o_six, floyd, intercontinental, mandarin, four_seasons, hyatt_miami, kyu, dolores, novecento, joes, capital, key_west, south_beach, everglades, seaaquarium]
        return places
    }
    
    static func getChoices() -> [Choice]{
        var choices: [Choice] = []
        choices.append(contentsOf: ChoiceType.allValues().map({ f in f as Choice }))
        return choices
    }
    
}
